### PR TITLE
[FCE-250] Add formatters and linters for ios-client, android-client and react-n…

### PR DESCRIPTION
**Pull request by karkakol**
## Description

Add linter to react-native ios code, make it consistient with native libs and update workflow files.
I removed `yarn format` and `yarn format:check`. Now there are in every repo `yarn lint` and `yarn lint:check`. Also added `yarn setup` command and updated `pre-commit.sh` script.

## Motivation and Context

Make all files linting and formating consistient across packages.

### CODE REVIEW

**Review by graszka22 — COMMENTED** [review]
I tested it on a fresh clone and running `yarn lint` made changes in android-client and react-native-client android code. Also the ios code is not formatted, a warning is thrown instead even though it's a simple indentation issue and could be auto formatted.

**Comment by graszka22** [comment]
`yarn lint` still changes the android code
`yarn format` also changes code but only in react-native android code
also it looks like `yarn format` doesn't format code for android client?

**Comment by karkakol** [comment]
> `yarn lint` still changes the android code `yarn format` also changes code but only in react-native android code also it looks like `yarn format` doesn't format code for android client?

Fixed. 
Description tells how this will work

**Comment by graszka22** [comment]
```
Now when yarn format command formats and lints native rn-client files and yarn format:check checks native rn-client files, yarn lint and yarn lint:check only works for js repos
```
isn't it too complicated? I just want one command that does everything :p Eventually two - one for formatting, second for CI.

**Review by mironiasty — APPROVED** [review]

**Review by graszka22 — APPROVED** [review]

**Pull request merged**
